### ISSUE TITLE
TypeScript error

### ISSUE THREAD

**Issue by jeremypeters** [themesberg/flowbite-svelte-icons#11]
Getting the error `Module '"flowbite-svelte-icons"' has no exported member 'Icon'` for the following:

`import { Icon } from 'flowbite-svelte-icons';`

v0.4.1

**Comment by shinokada** [comment]
I just released a BREAKING change. Please read the [docs](https://flowbite-svelte-icons.vercel.app/).
I apologize for the inconvenience.

**Comment by MoritzStefaner** [comment]
I ran into the same issue, it would be great if breaking changes would trigger a new major version number (1.x → 2.x)

**Comment by Bouchtaoui** [comment]
> I just released a BREAKING change. Please read the [docs](https://flowbite-svelte-icons.vercel.app/). I apologize for the inconvenience.

The link is dead 💀

**Comment by shinokada** [comment]
The new URL is https://flowbite-svelte.com/icons/svelte-4.
