### ISSUE TITLE
SvelteKit Support?

### ISSUE THREAD

**Issue by nash-an** [themesberg/flowbite-svelte-icons#12]
Not sure what's happening, but latest version (0.4.3) on SvelteKit has no exported values. 

Within `+layout.svelte` I am unable to import anything from the library.

```js
import { Icon } from 'flowbite-svelte-icons';
import { AddressCardSolid } from 'flowbite-svelte-icons';
```

Neither of these imports work. The values just don't exist.

**Comment by shinokada** [comment]
Please read the [docs](https://flowbite-svelte-icons.vercel.app/).

You don't need to import `Icon` any more.

```
<script>
  import { AddressCardSolid } from 'flowbite-svelte-icons';
</script>

<AddressCardSolid />
```

The compiled size is much smaller now.

**Comment by nash-an** [comment]
Sorry, it was just meant to be an example as nothing seems to work for me.

```
Error: <ChartPieSolid> is not a valid SSR component. You may need to review your build config to ensure that dependencies are compiled, rather than imported as pre-compiled modules. Otherwise you may need to fix a <ChartPieSolid>.
```
I'm able to import things now... but I'm getting this error.
I have it installed as a dev dependency, so that's not the issue.

**Comment by shinokada** [comment]
Which version are you using?

**Comment by nash-an** [comment]
0.4.3

Running `npm run check` gives me this error

```
Error: Module '"flowbite-svelte-icons"' has no exported member 'ChartPieSolid'. (ts)
```

**Comment by shinokada** [comment]
Can you share your GitHub repo or stackbiltz?

**Comment by nash-an** [comment]
I'll try to reproduce the issue in a smaller repo, I cannot share the full one I'm working with.

**Comment by shinokada** [comment]
Please make sure to follow the installation guide at https://flowbite-svelte-icons.vercel.app/
