### ISSUE TITLE
Module '"flowbite-svelte-icons"' has no exported member 'IconSolid'

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte-icons#14]
Thank you for this update even if it breaks a bunch of stuff.
I was trying the example `Custom Default Icon ` from the docs and I get this error:

`Module '"flowbite-svelte-icons"' has no exported member 'IconSolid'`

I tried the exact code from the docs

**Comment by JackNeto** [comment]
Hmm, I'm getting the similar error importing any icon:
```
import { AngleLeftSolid } from 'flowbite-svelte-icons';

Module '"flowbite-svelte-icons"' has no exported member 'AngleLeftSolid'.ts(2305)
```


Using version `flowbite-svelte-icons": "^0.4.4"`

**Comment by shinokada** [comment]
Mmmm. I'm not able to produce it.
I need more details.
Can you remove node_modules directory and pnpm-lock.yaml and install it again?

**Comment by JackNeto** [comment]
I did that, no change.

This seems to work:

`import AddressCardSolid from 'flowbite-svelte-icons/dist/AddressCardSolid.svelte';`
