### ISSUE TITLE
ProfileCardSolid is missing

### ISSUE THREAD

**Issue by luko0610** [themesberg/flowbite-svelte-icons#19]
The icon ProfileCardSolid is missing.
I am willing to create a PR for this.

**Comment by shinokada** [comment]
It must be a new one. I will update it.

**Comment by luko0610** [comment]
Appreciate it. Thanks.

**Comment by shinokada** [comment]
It seems the [original icons](https://github.com/themesberg/flowbite-icons/tree/main/src/solid/user) do not have it even though [outline](https://github.com/themesberg/flowbite-icons/tree/main/src/outline/user) has it.
And their folder contents are not consistent.
Please create an issue at https://github.com/themesberg/flowbite-icons/issues.
