### ISSUE TITLE
How to remove icon border when clicked

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte-icons#20]
When an icon is clicked it always gets a border around it. I don't understand what is the purpose of that.
How can I remove this behaviour? Is this a bug or a feature?

**Comment by shinokada** [comment]
Can you try this?

https://flowbite-svelte-icons.vercel.app/#Unfocusable_icon

**Comment by JackNeto** [comment]
Yes, I have tried setting `tabindex="-1"` which prevents the element from getting focus when using the `TAB` key. 
This doesn't prevent the icon from getting a border when the user clicks on it. For example an button with an icon get a weird border on the icon. 

You can see this on the documentation here: 
https://flowbite-svelte.com/docs/components/buttons#Icon_buttons
![Screenshot 2023-12-30 at 2 56 11 PM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/89aa3442-e2cd-442c-b6e2-ec55568e566f)

**Comment by shinokada** [comment]
Can you try adding `style="pointer-events: none;"`?

**Comment by JackNeto** [comment]
That works great, thank you
