### ISSUE TITLE
Add video-play icon

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte-icons#22]
Would you be able to add the `video-play` icons? They already exist on the Flowbite Icons https://flowbite.com/icons

Thank you in advance.

**Comment by shinokada** [comment]
It must have a different name. If flowbite has it, then it must be there. Please browse the icon to find it out.

**Comment by JackNeto** [comment]
Ok, I found it. The naming is off so I keep getting tricked into thinking it's not there.

![Screenshot 2024-01-27 at 9 50 10 AM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/4d58cd8d-3ebc-4469-a7c9-3dca2c00792d)
![Screenshot 2024-01-27 at 9 47 18 AM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/0d3169c8-9326-428a-a9f6-7105c42889c8)
![Screenshot 2024-01-27 at 9 47 58 AM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/283beba9-77ab-4c9a-9683-fb8733682b63)
![Screenshot 2024-01-27 at 9 48 14 AM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/e14cb121-9376-43af-be8a-78f3acb744e2)

**Comment by shinokada** [comment]
I use the file name for the icon names. But flowbite-icons uses something else.
