### ISSUE TITLE
XCompanySolid was deleted

### ISSUE THREAD

**Issue by 0xCaponte** [themesberg/flowbite-svelte-icons#23]
Not sure if this was on porpuse but the component XCompanySolid.svelte was deleted with the commit [16aeffc](https://github.com/themesberg/flowbite-svelte-icons/commit/16aeffcca4f71a2868a466ec52cfd2a1a08838a3) and there doesnt seem to be a replacement.

**Comment by 0xCaponte** [comment]
I checked the vercel app and didnt find the one, however I do find it under [themesberg/flowbite-icons]( https://github.com/themesberg/flowbite-icons/blob/main/src/solid/brands/X.svg) and in [https://flowbite.com/icons/](https://flowbite.com/icons/)

Maybe it is being overwritten by something or the naming doesnt match the expected convention. 

This is by no means a complain, it is just to let you know. I am sticking with version 1.0.3 as I really dont need many icons but thought you might want to know.

**Comment by shinokada** [comment]
There is another file called x.svg and then I run a script, it overwrites X.svg. I created an issue [here](https://github.com/themesberg/flowbite-icons/issues/26).

**Comment by shinokada** [comment]
I rename the file (and there are more strange files) and now it is TwitterSolid.svelte.
Install the latest, flowbite-svelte-icons@1.2.0 and let me know.
