### ISSUE TITLE
Missing icons because current version is not synched with upstream version

### ISSUE THREAD

**Issue by ZaDarkSide** [themesberg/flowbite-svelte-icons#25]
Current version is not synched with upstream version, maybe a Github Action or some automated script can pull icons automatically so this is always up to date?

The missing icon for me was `PieChartOutline` it's called `chart-pie` on Flowbite Icons, others might be missing also because they update often.

Also naming is a bit wonky you could keep compatibility with old naming by creating aliases so people don't complain.

**Comment by shinokada** [comment]
Please try the latest version.

**Comment by ZaDarkSide** [comment]
Thank you I appreciate the update, but the icon is still missing and maybe doing this manually isn't a great ideea and an automated script would work best?

Here is a picture for it maybe is more clear what icon is missing
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/291278/e6752bd2-2963-4363-bc15-8b022f0fc0d0)

**Comment by shinokada** [comment]
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/147320/55db4465-c9d6-4038-843b-27179f946c3b)

It is there, https://flowbite-svelte-icons.vercel.app/outline.

**Comment by ZaDarkSide** [comment]
You are right, I'm sorry but the name doesn't contains `pie` will throw off anybody...was expecting either `ChartPieOutline` or `PieChartOutline` because the original has `pie` in the name `chart-pie` the naming is still wonky.

**Comment by shinokada** [comment]
Naming of Flowbite-svelte-icons are from svg file names and please use https://flowbite-svelte-icons.vercel.app/ to find icons. 
Flowbite-icon site uses different names.
