### ISSUE TITLE
BriefcaseOutline icon has wrong name

### ISSUE THREAD

**Issue by JackNeto** [themesberg/flowbite-svelte-icons#26]
Here's the `BriefcaseOutline` I was looking for:

![Screenshot 2024-02-04 at 10 06 03 AM](https://github.com/themesberg/flowbite-svelte-icons/assets/136458/2e5e3a4b-fd12-4f28-9b9e-2149b0a21c2f)

**Comment by shinokada** [comment]
The icon names are created from SVG file names. Flowbite-icon has different naming from file names.

**Comment by JackNeto** [comment]
I'm sorry @shinokada  but, how is this completed?
The `BriefcaseOutline` icon name is not only clearly wrong but it is also taking up another icon's name.

**Comment by shinokada** [comment]
As I stated it before, all the icon names are from SVG file names. I use a script to automate all the icons to create svelte icon files. If you think the file name is not correct then please create an issue at https://github.com/themesberg/flowbite-icons/issues.

**Comment by JackNeto** [comment]
Ok, thank you for the clarification. 
I filled a ticket: https://github.com/themesberg/flowbite-icons/issues/32

On a side note, you can manage this repo as you wish but currently it is unusable due to all the broken icon names (even if it's not your fault) and as such the ticket should not be closed.

**Comment by JackNeto** [comment]
> It was a BREAKING change when the major version is released.

How would anyone know this? You don't seem to have release notes.

**Comment by shinokada** [comment]
Please read:
- https://semver.org/
- https://github.com/conventional-changelog/standard-version.

**Comment by JackNeto** [comment]
That's right, semantic versioning doesn't require you to explain what breaks in the new release.
I'm just saying that it would be nice if you just gave everyone a heads up that the repo is unusable and we shouldn't waste our time installing it because a bunch of icons are named wrong.
