### ISSUE TITLE
Check Circle Solid is missing in flowbite.-svelte-icons

### ISSUE THREAD

**Issue by dfaua** [themesberg/flowbite-svelte-icons#27]
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/65195811/e8e3191b-a7b7-4487-9a65-f34d2bb0097c)

**Comment by shinokada** [comment]
Are you using the latest version?

**Comment by dfaua** [comment]
I was using wrong name. It works now, thank you!

https://flowbite-svelte.com/docs/components/card#Testimonial_card pricing card here suggests name "CheckCircleSolid".

**Comment by shinokada** [comment]
Yap, that's outdated.
