### ISSUE TITLE
Missing CloseCircleSolid + CloseCircleOutline icon

### ISSUE THREAD

**Issue by bastienriviereocd** [themesberg/flowbite-svelte-icons#29]
They got deleted in this commit: https://github.com/themesberg/flowbite-svelte-icons/commit/16aeffcca4f71a2868a466ec52cfd2a1a08838a3

For reference: 
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/134399729/70b92629-4cda-46c3-8ca6-6de798f8592f)

**Comment by shinokada** [comment]
All the icon names come from the file names.
Please search at https://flowbite-svelte-icons.vercel.app/outline .

**Comment by bastienriviereocd** [comment]
Ah! Didn't know this website, thanks!
