### ISSUE TITLE
Missing ArrowDownSolid and ArrowDownOutline in 1.3.1

### ISSUE THREAD

**Issue by herohead049** [themesberg/flowbite-svelte-icons#30]
I was using ArrowDownSolid from version 1.0.2 and then recently updated to version 1.3.1 and found that ArrowDownSolid and ArrowDownOutline is missing.

**Comment by shinokada** [comment]
Please find the new names at https://flowbite-svelte-icons.vercel.app/outline.

**Comment by herohead049** [comment]
I have checked it out and I do not see any icon that represents an ArrowDown. If you search for Arrow there is no ArrowDown. There is ArrowUp, ArrowRight, ArrowLeft but no ArrowDown.  Looks like the last time it was there was version 1.03. I have had to revert back to version 1.0.3

![image](https://github.com/themesberg/flowbite-svelte-icons/assets/5099990/677caf3c-f5c8-49c1-8396-ab8aede4edcb)

**Comment by herohead049** [comment]
Ok thanks. I have create an issue as instructed.
