### ISSUE TITLE
CogSolid vs GearSolid

### ISSUE THREAD

**Issue by jonathanbaugh** [themesberg/flowbite-svelte-icons#32]
I noticed a small error when trying to import `CogSolid`. The import fails, but `GearSolid` seems to be the correct icon with an incorrect name. `CogOutline` is available. I'm using version 1.4.0.

Thanks for maintaining this icon set! I read in some other comments that it's generated via a script, but let me know if I should submit a PR.

![image](https://github.com/themesberg/flowbite-icons/assets/4481475/6de03041-0cec-41ac-84a4-fd94b1c61d31)
![image](https://github.com/themesberg/flowbite-icons/assets/4481475/d2d53836-61f8-4542-b187-0aba98668899)
![image](https://github.com/themesberg/flowbite-icons/assets/4481475/7c85328a-e643-4386-bdba-4e7bb912e43c)

**Comment by shinokada** [comment]
I can't find GearSolid in index.js, https://github.com/themesberg/flowbite-svelte-icons/blob/main/src/lib/index.js

**Comment by jonathanbaugh** [comment]
Sorry about that. After reinstalling dependencies the error went away. Thanks for looking into it!
