### ISSUE TITLE
Argument of type 'typeof CogOutline' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'

### ISSUE THREAD

**Issue by brobee** [themesberg/flowbite-svelte-icons#36]
Brand new install following the readme, but the the code below gives me this error:
```
<script>
	import { CogOutline, DotsVerticalOutline, DownloadSolid } from 'flowbite-svelte-icons';
</script>

<CogOutline />
```
Argument of type 'typeof CogOutline' is not assignable to parameter of type 'ConstructorOfATypedSvelteComponent'.
  Type 'typeof CogOutline' provides no match for the signature 'new (args: { target: any; props?: any; }): ATypedSvelteComponent'.
Possible causes:
- You use the instance type of a component where you should use the constructor type
- Type definitions are missing for this Svelte Component. If you are using Svelte 3.31+, use SvelteComponentTyped to add a definition:
  import type { SvelteComponentTyped } from "svelte";
  class ComponentName extends SvelteComponentTyped<{propertyName: string;}> {}js(2345)

**Comment by shinokada** [comment]
I can't reproduce the problem.

Are you using v1 or v2?
Can you create a https://stackblitz.com/ ?

**Comment by brobee** [comment]
I don't know honestly, just installed with: pnpm i -D flowbite-svelte-icons
Here is the stackblitz.com. 
[https://stackblitz.com/edit/vitejs-vite-w42aeb?file=src%2FApp.svelte](url)

Obviously It won't give error on mouseover, but when I use the icon component, demo app does not appear, so there could be a problem. Appreciate your help.

**Comment by shinokada** [comment]
You have `2.0.0-next.3` on Svelte 4.
Install 1.4.1.

```
pnpm i -D flowbite-svelte-icons@1.4.1
```

**Comment by brobee** [comment]
Thank you so much! What is the best way to find out such a compatibility issue?

**Comment by shinokada** [comment]
Please read the documentation, https://flowbite-svelte-icons.codewithshin.com.

**Comment by brobee** [comment]
thank you! We can close this ticket!
