### ISSUE TITLE
Probable typo in documentation for icon size 'md'

### ISSUE THREAD

**Issue by gclinch** [themesberg/flowbite-svelte-icons#37]
In the icon size table https://flowbite-svelte-icons.codewithshin.com/#Size 'md' size is described as using 'w-5 h-**6**'

That should probably be 'w-5 h-**5**', as seen in the tables used within the components themselves, eg: https://github.com/themesberg/flowbite-svelte-icons/blob/4300696abdc6ff41364a5610cdeb8859bd0e70bc/src/lib/ArrowUpSolid.svelte#L16

**Comment by shinokada** [comment]
Thanks. I just fixed the typo.
