### ISSUE TITLE
CogSolid does not exists

### ISSUE THREAD

**Issue by WyWlf** [themesberg/flowbite-svelte-icons#38]
### Describe the bug

![image](https://github.com/themesberg/flowbite-svelte-icons/assets/117328165/18b29037-e18a-4ebc-913a-bd237b050b3d)

as what the title says only CogOutline is fine

### Reproduction

![image](https://github.com/themesberg/flowbite-svelte-icons/assets/117328165/aad2b578-b133-48e5-ad72-dfaedc765d79)

### Version and System Info

```shell
"flowbite-svelte-icons": "^1.0.2",
```

**Comment by shinokada** [comment]
Please use the latest version.

```
pnpm i -D flowbite-svelte-icons@latest
```

**Comment by WyWlf** [comment]
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/117328165/e64d9ac1-c68b-437f-ab77-ea4f902e1014)
![image](https://github.com/themesberg/flowbite-svelte-icons/assets/117328165/2e02cdef-cf88-4a7d-8ee5-ca2aca2882d0)

still got the same problem

**Comment by shinokada** [comment]
It does!..

https://svelte.dev/repl/594644f2b9cc45c8b2d4aaf27d9229eb?version=4.2.12

Restart your VSCode.

**Comment by WyWlf** [comment]
> It does!.
> 
> https://svelte.dev/repl/594644f2b9cc45c8b2d4aaf27d9229eb?version=4.2.12
> 
> <img alt="image" width="601" src="https://private-user-images.githubusercontent.com/147320/314485820-b9874ae2-a0b6-4617-8ca4-11f1547ab9e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MzU0NDAsIm5iZiI6MTcxMDkzNTE0MCwicGF0aCI6Ii8xNDczMjAvMzE0NDg1ODIwLWI5ODc0YWUyLWEwYjYtNDYxNy04Y2E0LTExZjE1NDdhYjllNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxMTQ1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYjgxN2U5OTg4YTVlMGUzMGUzZTgzZTdmYTMzN2IzM2MyMzc1ODAxNGZjYjc1NGFkNjJkYWIxYzNlYjVlNzQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.guGpRugg0nEzIAMO3McDtbbjlN_dDqtFuuxYAGHqkMI">
> Restart your VSCode.

got it working after the restart, that was pretty dumb of me lol thanks.
