### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by jjagielka** [themesberg/flowbite-svelte-icons#5]
Need to add to the installation procedure:

---

You must to your local `tailwind.config.js` :
```js
const config = {
  content: [
       ...
        "./node_modules/flowbite-svelte-icons/**/*.{html,js,svelte,ts}",
    ],
```
To make sure the classes used by `flowbite-svelte-icons` are included by the Tailwindcss.

**Comment by shinokada** [comment]
Thanks. I just updated it.
https://flowbite-svelte-icons.vercel.app/docs
