### ISSUE TITLE
Icon naming

### ISSUE THREAD

**Issue by hardyjosh** [themesberg/flowbite-svelte-icons#9]
Thank you for the great work on this package!

One question - for the `name` prop, why not use the names from the browser on the [Flowbite website](https://flowbite.com/icons/)?

You could also add a `style` prop for outline or solid.

It's minor but I've found myself searching icons.js in the dist a few times looking for the right name for my icon.

Sometimes it's the name from the Flowbite site with "-solid" or "-outline", but not always. Just now I was looking for outline "plus-circle", but in the package it's "circle-plus-outline"

**Comment by shinokada** [comment]
I use a script to convert all icons from [the Github repo](https://github.com/themesberg/flowbite-icons).
You can find all the names at https://flowbite-svelte-icons.vercel.app/icons. You can use a search function as well.
